### ISSUE TITLE
Research Springboot

### ISSUE THREAD

**Issue by KentZeng123** [Husky-Coding-Project/algo-visualizer#10]
Research how springboot can be used in our web app.

**Comment by AndrewZhang126** [comment]
https://spring.io/guides/tutorials/react-and-spring-data-rest/

Spring boot is a Java framework for building stand alone applications. Spring boot offers a REST API and you can use curl to retrieve data from Java backend in a JSON format. Below is sample code of JSON data retrieved using curl

<img width="608" alt="Screen Shot 2021-11-05 at 11 24 38 PM" src="https://user-images.githubusercontent.com/74576302/140600185-dea553fe-00a4-4865-ae75-2433ebcaed08.png">

The following is sample React code using the API to retrieve data. Properties (props) are values passed to a component that do not change (like parameters). States are data the component handles that can change. In this class, the state is the employees, which is populated with data retrieved from the server through the API call 
**client({method: 'GET', path: '/api/employees'}).done(response =>**


<img width="741" alt="Screen Shot 2021-11-05 at 11 26 06 PM" src="https://user-images.githubusercontent.com/74576302/140600204-08aef1f1-e7ef-4678-a9cc-1da1c5ecde1f.png">
