### ISSUE TITLE
BFS Queue needs smoother animation

### ISSUE THREAD

**Issue by nith2001** [Husky-Coding-Project/algo-visualizer#58]
Whenever the Queue component used on the BFS page updates to the next step of BFS, it has very sharp transitions and doesn't have the smooth enter/exit animation that the Stack component has. This is because the Queue component involves moving ALL of the items of the queue down whenever an element leaves, unlike the Stack component. Whenever animation is applied, there are duplicate items that flash on and off for a bit, which need to be made invisible or removed somehow. I have a strong feeling that the way the Queue component is designed to be filled might need some changing in order to support animation.

Priority: Low
Difficulty: Medium/High

**Comment by davin12345678910** [comment]
We have got something planned out, but will need to figure out why only one case works, even though we have an if/else for one case and another case. Maybe it is a limitation with CSSTransitions
